stages:
  - build
  - test
  - deploy

before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version

dummy job on windows:
  stage: test
  script: 
    - echo ok
  tags:
    - windows

build_solution:
  script: 
    - echo "building..."
    - msbuild -target:Build -r TapTrackAPI.sln
  tags:
    - powershell
  stage: build
  
pack and deploy job:
  script: 
    - echo "deploing.."
  tags:
    - windows
  stage: deploy