version: "3.2"

services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

  client:
    build:
      context: ./angular/taptrack
      dockerfile: Dockerfile
    network_mode: "host"