version: "3.2"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    restart: always
  
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    
  client:
    build:
      context: angular/taptrack
      dockerfile: Dockerfile
    ports:
    - 3000:8080