version: "3.2"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - 80:80
    restart: always
  
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    
  client:
    image: hernantos/client
    ports:
    - 3000:80